export namespace Configuracion {
  export const hasNotificacion = "LU3RRjfXHvvl"
  export const mensajeCambioClave = "Su contraseña ha sido actualizada correctamente. Si no ha sido usted, la puede recuperar mediante la funcionalidad del sistema con su correo electrónico"
  export const mensajeCreacionUsuario = "Se ha registrado correctamente en el sistema de validación, su correo servirá como usuario y su contraseña es: "
  export const mensajeRecuperarClave = "Su nueva clave generada para el sistema es: "
  export const urlCorreo = "http://localhost:5000/correo"
  export const urlMensajeTexto = "http://localhost:5000/sms"
  export const asuntoCambioClave = "Cambio de contraseña"
  export const asuntoCreacionUsuario = "Registro en el sistema"
  export const saludo = "Hola"
  export const destinoArg = "destino"
  export const asuntoArg = "asunto"
  export const mensajeArg = "mensaje"
  export const hashArg = "hash"
}
